* Notes
** Jersey dies at the end of book 4 and finds himself in the matrix-like afterlife, tenatively called half-life.
** Half-life
   Every day he wakes up in a new place in a new time.
   The rules are explained to him very early.
   If he dies his original image will simply be rebooted and the half-life will start over again.
   In this sense humans are given an experience similar to but greatly superior to the life they had on earth.
   No one dies and lives a life of rich variety.

** On most days Jersey wakes in periods with not enough tech to do anything
   He usually tries to invent tech to hack out of the matrix.
   Typically he doesn't get very far.
** Throughout his journey he pioneers the technique of quarter-life
   By ignoring senses and focusing on internal thoughts he can speed time.
   This allows him to think very quickly and get a lot done on the days that he has access to tech.
   When he dies the computers reward him for greatly decreasing the processing power of humans.
   This reward is a "life in a day" where his final, post-death day is the length of a human life.
   He uses this to hack back into Emily Williams body, but since it's a fresh copy he has no memories.
   The above mentioned death was at the hands of his best friend/lover/traveling companion.
   The AS manipulated his companion into killing him because they were worried he was getting too powerful.
* The Library
** Description
*** The Librarian
**** Harmless old man who describes things in simplest possible terms
     What's a library card do? "It allows you to checkout books, of course."
     "I don't need a power glove/card catalog/computer because I have a library card."
     What does a donation of one HQ get us? "A tote bag and our gratitude."
     What does a donation of one million HQ get us? "A tote bag and our gratitude."
*** Waiting Room
    Similar to the library in the nightvale book
    Childrens section, reading tables, staff picks, old (broken) computers, card catalog, and community message board.
    Jersey wanders around leafing through worthless books, trying to use the computers, and utterly confused.
*** Specters
    Jersey sees one in the waiting room.
    Because days are so long in the library (decades) some people stay there forever.
    If they go to sleep they can get out instantly.
    Specters are people who have stayed too long and forgot to take care of themselves.
    Some are almost zombie like (like the first one).
    Others are floating aparitions (ghostbusters for inspiration?).
    The only danger they pose is to hide books. Some are even helpful.
*** Library Card
    Prized goal of the library, gives access to library when not in library via "book checkout".
    Locate in the center of the labrinth, a maze where the librarians keeps fantastical creaters he invented.
    At the center of the labrinth is a boring looking form that they fill out with ink and take back to get a card.
    The librarian takes the form, processes it by hand and gives Jersey a library card.
