* Notes
** 3/25/16 - The Time Travelling Musician
  Book 7 is a variant of the time travelling musician story I came up with ca. 2007. A semi famous singer is peaking in his career before making it big. He is approached by his agent who informs him that the band is taking on another lead singer. He can't dispute because he's already signed the contracts. The second lead singer is himself from the future. He reluctantly agrees half suspecting that it's some weird publicity stunt. He doesn't interract much with him future self and plays a few shows. His first weird interraction he has awkward sex with himself, plays a few shows where they put on the persona of gay lovers, and then fights with himself and storms off. He becomes homeless and, desperate for money while his future self continues with the band, he enrolls in medical experiments.

  On the second experiment he is informed that his brain is rarely shapped in such a way that it is the only known brain that will work with a newly invented time machine. They force him to sign wavers, acknowledging that the odds of him surviving the experiment are next to none. When he tries to tell them that he is destined to survive the experiment they laugh him off as insane. He goes back in time and joins the band with himself.

  It's horribly awkward and difficult. When he finally sleeps with himself he is at first depressed, but then gets a sudden sensation of freedom. His fate is no longer decided and is free to choose a path unhindered by knowledge of the future.
** 2/25/16 The Hive mind and the future
*** Books 6/7 interim
  When the remaining humans (either only Belmonts or a few dozen others) stop Shiva at the end of book 6 they posess control over the ever increasing black matter and have become time walkers. This is a huge amount of leverage since it makes them militarily invincible. They secure 0.2% of the nets (fixed to grow with inflation) and a new filter that states that senscients cannot conspire against or with humans. They also negotiate legal admin access for timewalkers and legal user status for the ghosts who live in the 0.2% of the nets.

  As a concession, humans agree to [lose breeding priviliges](). Senscients are concerned that human breeding is pinned to food supply and habitat (both not pinned to increased by moore's law) which means that they can overwhelm the limited earth ecosystem. However, time walkers can fork and spread to multiple bodies and the ghosts in the machine (lol) can act as serrogate souls to the core huma, much like Kelly and Jan did in Book 2. This ability is enhanced by entanglement to black matter and is collectively known as the [Timewalker Algorithm](). The Timewalkers resurrect the ghosts this way, thus the population of earth at the start of Book 7 is the original admins each in control of 10-100 slave members of the hive minds.

[lose breeding priviledges] Good potential side story is a human who doesn't know she is in the matrix trying to breed and eventually discovering that she's dead in the matrix.

[Timewalker Algorithm] The ability to sustain hiveminds and the ability to wander through time are mathematical transforms of each other. Senscients only have access to a quatuum/digitizable version of this, giving them encryption that can't be broken by the Timewalker Algorithm. The ability to run this without black matter is mathematically proven, but not well understood. Much of the business plot of Book 7 centers around rumors of a digitizable and non-quantum version of this algorithm nicknamed "Ghostrunner".

*** The science
  A hivemind is composed of multiple disparate parts of one mind. It is not simultaneously thinking the same thing but instead it is a cluster of people periodically "synced" with each other. All plot and narrative in the traditional sense are between individuals of separate hive minds. If two people of the same hive mind get too close, their memories fuse and they share experiences of the hive mind with each other.

  Thus members of a hive mind have two identities. The characters are individuals, who happen to be a part of the same ovrall being, much like when a normal human goes on vacation they are a distant representative of the person they would be in an office or social setting. Each person is a second, imaginary character who only exists as part of a shared dillusion. The characters of the story live with the memories of the hive mind, but we only truly see it when they are attempting to merge.
** Plot
*** Insurrection (potentially a separate short story)
    The main character is a male who is part of a mostly male hive mind specializing in the production of something or other. The main character is poor, an lives a life of minimal luxury, content to experience direct pleasure through the memories of the superior hive mind. For pleasure the main character goes to bars, drinking an accomplishing nothing while recalling stories of the great hedonistic conquests of the alpha of the hive mind. He is fully aware of these experiences, being able to recall them as if he were there, but doesn't actally experience them directly. When the main character is so drunk an wasted that he cannot remember his thoughts, he thinks seditious thoughts, envious and hoping to become the alpha to experience them himself.

    While at his "day job" (whatever hive minds do for a living) he works hard, supressing any thought crime but simultaneously aware that these thoughts are there. Around the water cooler he hears rumors of a coup within a hive mind where the members overthrew the alpha. The first third of the story focuses on his angst, masked by alcohol.
*** Mind Shatter (a murder mystery)
    The bigger plot of the story starts when one of the hive minds is murdered. None of its members die (although the prime is secured away somewhere), but the hive mind itself is killed by a mysterious process nicknamed "Mind Shatter". All of the secondary processes (humans) are disconnected when the private key is revoked causing them to lose most of their memories (encrypted now behind the lost key).

    This spreads paranoia in the other hive minds. Did a rival Timewalker kill him? Have the Scenscients constructed a cyber weapon capable of killing a hive mind? Why wasn't this deployed against more Timewalkers? The now dead hive mind was rumored to have been working on (and supposedly was successful) at creating the Ghostrunner Algorithm, which would either cement humans as a dominant force in the solar system or give the Senscients an advantage over humanity. The "business plot" of the story is the remaining hive minds fighting each other to gain control of the fragments of the dead hive mind to win the prized Ghostrunner Algorithm.

    Each of the fallen of the hive mind are voiced by different musicians. Either the intro to the story or suplimentary materials are the stories of the various members pre-hive mind living in the cloud. Then, Paycheck style, they join the cloud and [wakeup years later]() with no memories of their time in the hive. Unlike paycheck, they can unlock memories of their time in the hive because fragments are burried and not encrypted by the forgotten key.

[wakeup years later] Like a bomb going off in movies, they awake dazed, ears ringing lying on the ground, completely unaware of anything around them.

    In general hive mind members are selected from "heaven", the billions of human minds archived on the nets. Each hive mind uses some selection criteria and, as there are ~10 billion souls and only <100 hive minds, each hive mind has access to a huge number of candidates. So a fraction of humanity lives in each hive minds matrix, continously being evaluated for selection.

    The dead hive minds matrix is late 90s America with scarcity turned off. Pepole are allowed to do anything they want outside of [something forbidden](). This can be writting programmings, cheating at a video game, doing a drug, killing someone, saying a forbidden word three times (each member came from a different challenge). In some of these matrices, the member is selected immediately after doing the forbidden act. In others the person who breaks the rule becomes part of the clergy who admits the act is harmless but still tries to stop people from doing it. Such people only get selected after resisting the clergy or helping people commit the banned act. This selects people EXTREMELY skeptical about reality, which is why the dead hivemind was so brilliant, able to crack Ghostrunner and realize that taking its own life was the key to the salvation of mankind.

[something forbidden] different for each of the dead hive minds members because they are in different matrixes... the hive mind has access to about 100 million minds afterall, so is running ~10 matrixes
