* Notes
** Naming chapters
** Arrange everyone's stories into their own books.
** Begin each file "The Book of Durga - Chapter 9"
** Book of Melissa and Book of Durga are mostly linear
** The book of Shiva is intertwined and mis-ordered, but must be unlocked
* Potential Names
** Last and First Men
* Plot Outline
** Book 1: Durga
** Book 2: Kelly
*** Awake on ship
*** Meets Viki
*** Discovers Viki is a doll
*** Admin access
*** Viki Dies
*** Viki is reborn
*** Kelly returns to earth
*** The doll 
    - Kelly's doll has repeatedly failed at life
    - A minimalist life, her carreres were repeatedly depracated
    - Finally she got a job as a "doll" an empty brain
    - Three years of doll training, she came in bottom of her class (failing again)
    - As a backup doll for venus, isn't needed until Kelly advances to user status
*** Kelly gains super user status
** Book 2.5: Offiline Mode
*** How to unlock offline mode
    Jan's chapters contain numerous references to "I didn't understand so I had to use offline mode to understand"
    Certain footnotes return an Http418 - Information not available while online
    Several times Jan encounters HTTP418, and goes offline. <hr> and then suddenly she understands
    This <hr> is characteristic, and indicates ofline content is available
    Leave hints such as transitions that don't make sense, "Jan was ripped out of online [+hangover]", and multiple <hr>s in a row
    If you're offline and try to save (leaving a chapter triggers bookmark save), offline chapters are unlocked
    When online, offline chapters are not visible
    At the end of book 2, Kelly says that she's "learned the value in unplugging every once in a while"
    This footnote triggers an "unplug" opiton in displays
** Book 3: Jan + Shiva
*** Notes on Meg (Born for this)
**** When Jan first asks Meg why she's doing this (if she's not on TV)
    she says "This is not TV, this is art. It takes acquired minds,
    to taste this wine. You can't down it with your eyes."
**** When asked why she killed the men who jumped them she says "I'm out
    If everyone's worth pleasing."
**** As they enter the black hole and leave terra, some one points out that
    all of Kelly's superuser plans are foiled. She points out that there 
    is a revolution brewing in reality TV (of all places)
    and that they will eventually overthrow the computers.
**** "Fences" would be a good song for the ghost of Meg in the net.
**** Meg leaves Shiva, not the other way around. Shiva leaves lot's of signals
    sort that are meant to get Meg back. When Jan gets to reality TV, Meg follows a similar
    signal to find her for the first time.
**** Every human who pisses off the computers is banished to reality TV to live off grid
**** Kelly and the ship of fools were deemed too dangerous
*** The filters:
    1 - Pay no attention to Titan
    2 - s/Io/Titan/gi
    3 - Ignore the girl
    4 - Forget about Yu-a
** Book 4: Paramore
*** Before the book
    - The revolution inspired by Meg (through traces and ghosts she left in the network)
    stages a coup in the form of a sci fi show (which is uncommon) paralleling the novel.
    - The final live action episode completes with a human becoming super human and taking over
    the internet. In the context of the show this is 
    - As the show ends, power goes out around the world and the revolution begins.
** Book 5: Series Finale (Lorde and Purity Ring)
*** Summary
    This book details the depracation of mankind
    After the events of book 4 Mankind enters into a "Battle Royal" style extinction
*** Mechanism
**** Choose your own narrator
     The same catastrophe following 4 or 5 people
     At the end of every chapter you're giving the option to follow one of them or another
     Story should be good no matter which path you take
     Read time for one path ~1 hour
     After you "win" you unlock free play mode that shows off every chapter
**** What a terrible night to have a curse
     Humans can only interract with and remember dream weavers while asleep
     Certain chapters appear in "odd hours" the hours that the reader didn't read books 1-4
* Easter Eggs
** Http404 - Random jokes (via url hash or something)
   - "Page not found. You're either a search engine spider or trying to hack your way into the future.
     If you are a robot, nice try and good luck.
     If you are a human, get off my lawn!"
** Http418 - Request is a teapot (Unlock code)
   Grants access to every hidden chapter predating the latest one
** Http419 - Request out of time/not available in current innertial frame
   Show relevant images or youtube videos (Blur's out of time) as an error page
** Http420 - Information not available online
   Shows "offline only" data
** README.*
   Every major chapter has a README file that is first person written by Shiva, often times showing Yu on Io
